### ISSUE TITLE
How do I get my calibration to save to EEPROM

### ISSUE THREAD

**Issue by rskissel** [OttoDIY/DIY#13]
Hello,

I cannot get my changes to save to the EEPROM.
I can make the adjustments and then "save", then "quit".

However, when I run another program the settings seem to have disappeared and Otto's ankles and hips have reverted to the positions they were in prior to calibration.

Thanks for the help!

**Comment by cparrapa** [comment]
Hi @rskissel just uploaded this week easycal give a try to that code
