### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by Kenzieen** [OttoDIY/DIY#16]
Hi, 

thats a newbie question, but every time I want to upload for example Otto_avoid - I got this error:

use of deleted function 'Otto::Otto()'

C:\Program Files (x86)\Arduino\libraries\Otto/Otto.h:32:7: note: 'Otto::Otto()' is implicitly deleted because the default definition would be ill-formed:

 class Otto

       ^

C:\Program Files (x86)\Arduino\libraries\Otto/Otto.h:32:7: error: no matching function for call to 'LedMatrix::LedMatrix()'

C:\Program Files (x86)\Arduino\libraries\Otto/Otto.h:32:7: note: candidates are:

In file included from C:\Program Files (x86)\Arduino\libraries\Otto/Otto.h:9:0,

                 from F:\Puplit\OTTO\Otto_BASIC\Otto_BASIC.ino:12:

C:\Program Files (x86)\Arduino\libraries\MAX7219LedMatrix-master/LedMatrix.h:33:5: note: LedMatrix::LedMatrix(byte, byte)

     LedMatrix(byte numberOfDisplays, byte slaveSelectPin);

     ^

C:\Program Files (x86)\Arduino\libraries\MAX7219LedMatrix-master/LedMatrix.h:33:5: note:   candidate expects 2 arguments, 0 provided

C:\Program Files (x86)\Arduino\libraries\MAX7219LedMatrix-master/LedMatrix.h:24:7: note: LedMatrix::LedMatrix(const LedMatrix&)

 class LedMatrix {

       ^

C:\Program Files (x86)\Arduino\libraries\MAX7219LedMatrix-master/LedMatrix.h:24:7: note:   candidate expects 1 argument, 0 provided

C:\Program Files (x86)\Arduino\libraries\MAX7219LedMatrix-master/LedMatrix.h:24:7: note: LedMatrix::LedMatrix(LedMatrix&&)

C:\Program Files (x86)\Arduino\libraries\MAX7219LedMatrix-master/LedMatrix.h:24:7: note:   candidate expects 1 argument, 0 provided

exit status 1
use of deleted function 'Otto::Otto()'

Could You help me ?

**Comment by cparrapa** [comment]
try the other avoids, update your libraries
