### ISSUE TITLE
The PDF is in english language available only

### ISSUE THREAD

**Issue by justinotherguy** [OttoDIY/DIY#31]
## Explain the problem:
We want to hold an OTTO building course. You have a wonderful description of the building process in PDF format. I'd like to translate this into German language. The PDF does not seem appropriate to do this.

Can you provide the source file from which you generate the PDF?
I'd like to use that as a basis for the translation.

Thanks in advance!

Regards, J.

**Comment by cparrapa** [comment]
Hi Justin

To Address the languages issues we find a way to make all building manual with almost no text and easier to understand, please check the latest version here:
https://wikifactory.com/+OttoDIY/otto-diy/file/Instruction%20manual/OttoDIY_Manual_V09_A6.pdf

We did our manuals in Illustrator, but is kind of difficult to modify, if you create your own club www.ottodiy.com/blog/clubs you will have access to them.

You are welcome.
