### ISSUE TITLE
Wrong data type for "O" in oscillator.h

### ISSUE THREAD

**Issue by TokenTotem** [OttoDIY/DIY#37]
At line 30 and 50 in oscillator.h, variable "O" is defined as a 'unsigned int' instead of 'int'. 
"O" have negative value such as when Otto walk (Otto9.cpp line 282).
There is no apparent impact on Arduino/Atmega but math results are out of wack on ESP32.

Solution: Change data type from "unsigned int" to "int" for variable "O" and "A" at lines 29,30,49,50 in oscillator.h

**Comment by cparrapa** [comment]
Hi @TokenTotem 
Thanks now we have a separated oscillator library for ESP
