### ISSUE TITLE
Active or passive buzzer?

### ISSUE THREAD

**Issue by cmcoffman** [OttoDIY/DIY#4]
All the documentation I can find says I need a "5V buzzer" but it's not clear if this is supposed to be an _active_ or _passive_ buzzer. Links to ebay and amazon will have both, and they look similar. 

The pictures look more like an active buzzer (which only is capable of producing one tone (I thinnk?), but I would think you would need a passive one.

I am unsure, any clarification?

**Comment by cparrapa** [comment]
Hi is DC voltage so is an active buzzer.

**Comment by cmcoffman** [comment]
Thanks!
