### ISSUE TITLE
Use more powerful micro controller

### ISSUE THREAD

**Issue by mohiuya009** [OttoDIY/DIY#41]
Please add support / code for esp32 (and pico) so we can have more rom (4mb) and built in wifi Bluetooth.

**Comment by sfranzyshen** [comment]
There are plans to add OttoNinja back into the OttoDIYLib & add full support for avr, esp, and pico with both native and external module bluetooth support. No timeline as of yet.

https://github.com/OttoDIY/OttoDIYLib/tree/devel
