### ISSUE TITLE
Add support for esp32 

### ISSUE THREAD

**Issue by guavuavcycayfayqvqu** [OttoDIY/DIY#44]
I really want to build otto ninja with esp32 that's fast and have 16MB flash(s3 ) and wifi for app control. But i couldn't find any tutorial for esp32. Is it possible? (I'm absolute noob). And can it fit inside otto ninja 3d printed parts?

**Comment by sfranzyshen** [comment]
Hi @guavuavcycayfayqvqu 

Please see my response to your issue over at the OttoDIYLib repo https://github.com/OttoDIY/OttoDIYLib/issues/70

**Comment by guavuavcycayfayqvqu** [comment]
> Hi @guavuavcycayfayqvqu
> 
> Please see my response to your issue over at the OttoDIYLib repo [OttoDIY/OttoDIYLib#70](https://github.com/OttoDIY/OttoDIYLib/issues/70)

Yes thanks
