### ISSUE TITLE
STL files in repo

### ISSUE THREAD

**Issue by justinotherguy** [OttoDIY/DIY#7]
Hi,

I think it would be nice to have the STL files directly in the github repo and not within the Zip file.
This way people would be able to see straight away, whether the STL files have changed.

The difference between two versions can not be made visible - but it would be easier to track the changes.

What do you think?

Regards, J.

**Comment by cparrapa** [comment]
Good idea i will add the stl files too so we people can rotate and see how they are like in thingiverse.
